services:
  ganache:
    image: trufflesuite/ganache-cli:next
    container_name: ganache
    command:
      - "--account=0x8e0a1f72c73f4a8d9d6b4f3c1a7b5d2c0a1e9f2b3c4d5e6f7a8b9c0d1e2f3a4b,100000000000000000000"
      - "--account=0x1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c,100000000000000000000"
      - "--account=0x3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d,100000000000000000000"
      - "--account=0x5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f,100000000000000000000"
      - "--account=0x7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b,100000000000000000000"
      - "--account=0x9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d,100000000000000000000"
      - "--account=0x0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e,100000000000000000000"
      - "--account=0x2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a,100000000000000000000"
      - "--account=0x4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c,100000000000000000000"
      - "--account=0x6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e,100000000000000000000"
      - "--account=0xb64be88dd6b89facf295f4fd0dda082efcbe95a2bb4478f5ee582b7efe88cf60,0"
    ports:
      - "8545:8545"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8545 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  mysql:
    image: mysql:8.0.43-debian
    container_name: store-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: prodavnica
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d:ro
    depends_on:
      - ganache
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 3s
      retries: 20

  owner-app:
    build: ./Owner
    container_name: owner-app
    depends_on:
      - mysql
      - ganache
    environment:
      DB_USER: appuser
      DB_PASS: apppass
      DB_ADDR: mysql
      DB_NAME: prodavnica
      DB_PORT: 3306
      DB_DRIVER: pymysql
      SECRET_KEY: JWT_SECRET_DEV_KEY
      WEB3_PROVIDER: http://ganache:8545
    ports:
      - "5001:5001"
    command: ["./run.sh"]

  customer-app:
    build: ./Customer
    container_name: customer-app
    depends_on:
      - mysql
      - ganache
    environment:
      DB_USER: appuser
      DB_PASS: apppass
      DB_ADDR: mysql
      DB_NAME: prodavnica
      DB_PORT: 3306
      DB_DRIVER: pymysql
      SECRET_KEY: JWT_SECRET_DEV_KEY
      WEB3_PROVIDER: http://ganache:8545
    ports:
      - "5002:5002"
    command: ["./run.sh"]

  courier-app:
    build: ./Courier
    container_name: courier-app
    depends_on:
      - mysql
      - ganache
    environment:
      DB_USER: appuser
      DB_PASS: apppass
      DB_ADDR: mysql
      DB_NAME: prodavnica
      DB_PORT: 3306
      DB_DRIVER: pymysql
      SECRET_KEY: JWT_SECRET_DEV_KEY
      WEB3_PROVIDER: http://ganache:8545
    ports:
      - "5003:5003"
    command: ["./run.sh"]

volumes:
  mysql_data:
